module.exports = {
  apps: [
    {
      name: 'perfilamiento-backend',
      cwd: './backend',
      script: 'dist/main.js',
      exec_mode: 'fork',
      instances: 1,
      autorestart: true,
      max_restarts: 5,
      min_uptime: '10s',
      time: true,
      watch: false,
      env: {
        NODE_ENV: 'development',
        PORT: 3000,
        FRONTEND_URL: 'http://localhost:9000',
        DATABASE_HOST: 'localhost',
        DATABASE_PORT: 5432,
        DATABASE_USER: 'postgres',
        DATABASE_PASSWORD: 'postgres',
        DATABASE_NAME: 'perfilamiento',
        DATABASE_SSL: 'false',
        DATABASE_SYNCHRONIZE: 'false',
        KEYCLOAK_ISSUER_URL: 'http://localhost:8080/realms/otic',
        KEYCLOAK_AUDIENCE: 'perfilamiento-api',
        KEYCLOAK_JWKS_URI: 'http://localhost:8080/realms/otic/protocol/openid-connect/certs',
      },
      env_production: {
        NODE_ENV: 'production',
        PORT: 3000,
        FRONTEND_URL: 'http://localhost:9000',
        DATABASE_HOST: 'db',
        DATABASE_PORT: 5432,
        DATABASE_USER: 'postgres',
        DATABASE_PASSWORD: 'postgres',
        DATABASE_NAME: 'perfilamiento',
        DATABASE_SSL: 'false',
        DATABASE_SYNCHRONIZE: 'false',
        KEYCLOAK_ISSUER_URL: 'http://localhost:8080/realms/otic',
        KEYCLOAK_AUDIENCE: 'perfilamiento-api',
        KEYCLOAK_JWKS_URI: 'http://localhost:8080/realms/otic/protocol/openid-connect/certs',
      },
      out_file: './logs/backend-out.log',
      error_file: './logs/backend-error.log',
      merge_logs: true,
    },
    {
      name: 'perfilamiento-frontend',
      cwd: './frontend',
      script: 'npm',
      args: 'start',
      exec_mode: 'fork',
      instances: 1,
      autorestart: true,
      max_restarts: 5,
      min_uptime: '10s',
      time: true,
      watch: false,
      env: {
        NODE_ENV: 'development',
        PORT: 9000,
        REACT_APP_API_BASE_URL: 'http://localhost:3000',
        REACT_APP_KEYCLOAK_URL: 'http://localhost:8080',
        REACT_APP_KEYCLOAK_REALM: 'otic',
        REACT_APP_KEYCLOAK_CLIENT_ID: 'perfilamiento-frontend',
      },
      env_production: {
        NODE_ENV: 'production',
        PORT: 9000,
        REACT_APP_API_BASE_URL: 'http://localhost:3000',
        REACT_APP_KEYCLOAK_URL: 'http://localhost:8080',
        REACT_APP_KEYCLOAK_REALM: 'otic',
        REACT_APP_KEYCLOAK_CLIENT_ID: 'perfilamiento-frontend',
      },
      out_file: './logs/frontend-out.log',
      error_file: './logs/frontend-error.log',
      merge_logs: true,
    },
  ],
};
